#!/usr/bin/env node
'use strict';

global.path = __dirname;
global.pp_version = require('./package.json').version;

const cli = require('commander');
const chalk = require('chalk');
const fs = require('fs-extra');
const Promise = require('bluebird');

const configManager = new (require('./app/config/ConfigManager'))(true);

configManager.wait().then(() => {
    cli.version(pp_version);
    
    let files = fs.readdirSync(`${global.path}/app/console/command`);

    for(let file of files) {
        if(file === 'ConsoleCommand.js') continue;
        require(`./app/console/command/${file}`);
    }
    
    if(process.argv.length < 3) return cli.outputHelp();
    cli.parse(process.argv);
});
